### ISSUE TITLE
[GameCube/Xbox] Crossplay Breakage

### ISSUE THREAD

**Issue by Matt-Swift** [fuzziqersoftware/newserv#179]
Well, we did a quick game with GC/XB crossplay to try it out, and it was funny.

### Xbox crashes if GameCube player is host

This doesn't happen the other way around - at the end of the bursting sequence, the Xbox player immediately hard crashes and has to reset their console.

[Log - Game Join.zip](https://github.com/fuzziqersoftware/newserv/files/13289972/Log.-.Game.Join.zip)

Here's 3 logs of game join attempts - 1 and 2 were the GameCube player hosting, whereas Log 3 is the Xbox player hosting (where it worked fine).

### Enemy status updates will cause strange effects to the other platform (XB Host)

We only played a quick forest run, but here's a couple of examples:

- When $PLATFORM1 attacks a Booma, $PLATFORM2 will see the Booma immediately freeze on their client (this freeze does not get send back to $PLATFORM1 at any point). This causes some strange issues as it seems that the updates when enemy is frozen do not propagate properly - if $PLATFORM1 kills the enemy during a freeze state, $PLATFORM2 will not see the enemy die and be unable to interact with them. Interestingly, this doesn't happen with *all* enemies, as Hildebears do not appear to be affected.
- When an android trap is used on enemies (that aren't Hildebears) by $PLATFORM1, $PLATFORM2 will see the enemy AI immediately break, and they will return to their spawn point as if all players have left the room. Furthermore, the targeting window for $PLATFORM2 will not display the enemy name/attribute, and just be a small black box instead.

### Boss does not sync state properly (XB Host)

That was to be expected, but fighting the Dragon caused a bunch of strange effects on $PLATFORM2 such as not moving properly, disappearing completely (and then re-appearing), among other issues.

Sound effects could still be heard as if the boss was still present, and the camera would move with their actions, but there was no interaction between players and the boss at all, except randomly when it re-appeared.

Here's a log of the entire game, I am currently too lazy to get specific logs but I will trawl through it if you're also lazy, which is understandable.

[Log - Crossplay.zip](https://github.com/fuzziqersoftware/newserv/files/13290334/Log.-.Crossplay.zip) - 183,802 lines

**Comment by fuzziqersoftware** [comment]
I think the in-game bugs are all fixed by 01f3ed7 - enemy flags and Dragon's position values were set incorrectly across the platform boundary. I tested with a Booma, but didn't try the Dragon or traps. I'll leave this open while I diagnose the crash at join time.

**Comment by fuzziqersoftware** [comment]
I've tried a couple of times, and I haven't been able to reproduce the crash when a GC player is the leader. I know it was a while ago, but do you remember any other details about the situation? (For example, were there two GC players already in the room or only one when the Xbox player joined? What levels were the GC players? Did they have any unusual items? Did anything significant happen in the game before the Xbox player joined?)

**Comment by Matt-Swift** [comment]
The crashing issue for Xbox still occurs on my instance of newserv, there's a log below.

Any Xbox player will crash if there is a GameCube player in the game at all, regardless of if they're leader or not.

[xbox.txt](https://github.com/fuzziqersoftware/newserv/files/13696024/xbox.txt)

**Comment by Matt-Swift** [comment]
We played a lot of hours of GC/Xbox crossplay today, and there didn't seem to be any major issues to report. We didn't play all the content or anything, but the issues are probably rare enough (other than the crashing bug... which might be me) that they can probably be submitted as separate issues.

As an aside, here's a set of 4 logs of GC joining Xbox and vice versa on newserv and another server which works.

[Other - GC joins Xbox.txt](https://github.com/fuzziqersoftware/newserv/files/13697935/Other.-.GC.joins.Xbox.txt)
[Other - Xbox joins GC.txt](https://github.com/fuzziqersoftware/newserv/files/13697936/Other.-.Xbox.joins.GC.txt)
[newserv - GC joins Xbox.txt](https://github.com/fuzziqersoftware/newserv/files/13697937/newserv.-.GC.joins.Xbox.txt)
[newserv - Xbox joins GC.txt](https://github.com/fuzziqersoftware/newserv/files/13697938/newserv.-.Xbox.joins.GC.txt)

**Comment by Matt-Swift** [comment]
Can confirm this issue is now fixed, and since crossplay in general seems to be good, I will raise specific tickets if things happen now.
